### ISSUE TITLE
Session Timeout Issue in Hawkbit

### ISSUE THREAD

**Issue by damontheimpulsive** [eclipse/hawkbit#1004]
How can we implement session replication in hawkbit? I am running two instances of hawkbit and I am facing a session expiration issue in my browser. I have tried with Redis in hawkbit but it is not working for me. Now I have tried **spring-session-jdbc** but while clicking on the Sign Button of  hawkbit I am getting the below error: 

**Communication problem Take note of any unsaved data, and click here or press ESC to continue.**

 I really need to implement session replication as the customer is asking for this feature for around 2 weeks. Please, help me with this issue.
I have attached the screenshot of the issue 
![HawkBit Session Error](https://user-images.githubusercontent.com/3033870/92119068-f24b5000-ee14-11ea-8d23-b577c831943b.png)

**Comment by schabdo** [comment]
Since hawkBit is single node there is no session replication out of the box as of today. I would also have tried with Redis but as @bogdan-bondar already stated in the chat (cf. [here](https://gitter.im/eclipse/hawkbit?at=5f5bb563d993b837e058ee88)) there seems to be a major issues (https://github.com/vaadin/spring/issues/340) and a fix won't make it into Vaadin-Spring. They suggest to use the sticky-session feature of you load balancer
