### ISSUE TITLE
Visual bug after migration to Vaadin 8

### ISSUE THREAD

**Issue by Sergey-G-dev** [eclipse/hawkbit#1011]
Hi everyone,
I noticed a visual bug in the Management UI after updating to the recent Vaadin version. In the Target Filter view, when I click on DS Auto-Assignment, the currently assigned Distribution Set is not being displayed. See screenshot below. Is this a known issue? Would appreciate solution proposals!

Edit: The issue only happens if there is a fairly long list of distribution sets and the assigned set is located in the lower section of the list (below 20-25 entries approximately).

![Missing DS](https://i.imgur.com/1xHjxm6.png)

**Comment by schabdo** [comment]
I created 26 distribution sets and was not able to reproduce it so far. But maybe I just picked the wrong item from the list by means it was not "down" listed enough 

@bogdan-bondar have you encountered something like that already? I could imagine that something with the backend size or the paging request is going wrong and the item to select in not in the list ?!?

@Sergey-G-dev Is at least the entry you have selected before part of the list?

**Comment by Molkenbur** [comment]
I just retested it and the configured value is shown in the field until the 40th distribution set from the list. Alle values behind the 40th entry are not shown.

**Comment by bogdan-bondar** [comment]
@Molkenbur @Sergey-G-dev thanks a lot for spotting this issue out! It was indeed hard to test everything during the migration, but I really appreciate that we have such a non-sleeping community ;) After investigating the issue I have found that the behaviour of initial item selection in combobox really does not work as intended/awaited. I have also found a similar issue posted in Vaadin Framework itself: [https://github.com/vaadin/framework/issues/9085](url). Nevertheless, I was happy to figure out that we can set the object with the required caption properties instead of just relying on Id. At least it fixes the visual representation of the item in combobox. You could find the relevant fix under the attached PR. I would be thankful if you could check it out (or wait until it is on master) and confirm the issue is resolved for you :)

**Comment by schabdo** [comment]
Thanks a lot for the quick fix @bogdan-bondar!

**Comment by Sergey-G-dev** [comment]
Thank you for the quick fix, much appreciated!
