### ISSUE TITLE
Unnecessary SQL queries when editing target filters.

### ISSUE THREAD

**Issue by Sergey-G-dev** [eclipse/hawkbit#1023]
**Problem description.**
A frequent use case is to modify a target filter. To do that, we have to navigate to "Target Filters" view and select a specific filter by clicking on its name. After that a detailed filter view is presented where the RSQL filter can be edited. At the same time, a database query is generated (based on the RSQL string) and performed and a list of matching targets is fetched from the DB and displayed on the page. But this operation is not necessary for the purpose of modifying a filter. It slows down the workflow and can increase the database load significantly, depending on complexity of the filter and the number of matching targets. 

**Improvement idea.**
A possible improvement would be to change the default behavior and not auto-load the list of matching targets when editing a filter. It would be still possible to fetch and display the matching targets by clicking on the magnifying glass symbol near the save button.

**Attempt to solve.**
After some code analysis and debugging sessions I found a method call which is resposible for performing the SQL query and populating the view with the retrieved targets. That is `targetFilterAddUpdateLayout.filterTargetListByQuery(proxyEntity.getQuery());` in the class `TargetFilterDetailsGridHeader.java`, line 144. After removing this line the view is not populated with the matching targets anymore. But the SQL query is still being generated and performed (in fact, two queries are being performed - one usual SELECT and another SELECT COUNT(..)). This does not make sense at all, because at this point it is unnecessary and the results are not presented anywhere. So I did some further investigation and discovered that there are several listeners attached to `AutoCompleteTextFieldComponent` class as well as its field `TextField queryTextField`. Apparently one of those listeners performs the query on each text change event in the Query Text Field (as long as it is valid). This looks like unnecessary overhead. I spent a good amount of time investigating the attached listeners, but until now I wasn't able to find the code that performs the SQL query. 

So if anyone could give me a hint where to look for that code, I would greatly appreciate it.

**Comment by Sergey-G-dev** [comment]
After further research, I've discovered that the issue is caused by `RsqlParserValidationOracle.java`. There is a text change listener which is attached to the query text field, which is triggered on every text change event (e.g. each key press) to validate the query syntax and generate auto suggestions for the next token. When doing this, it is performing (unnecessary) SQL queries in order to generate parse exceptions, which are then evaluated in order to validate the syntax of the query. So I've changed it so that instead of calling the repository method `targetRepository.findAll()`, only the `RSQLUtility.parseRsql(String rsql)` method is called to validate the query and generate exceptions. I've prepared the pull request to fix that: https://github.com/eclipse/hawkbit/pull/1028

**Comment by bogdan-bondar** [comment]
Thanks a lot for your interest and contribution to this issue! Indeed your explanation is correct and the issue you discovered is totally valid. However, the solution to this problem is more complex as seen from the first look. First of all, I thought that the changes you've proposed within #1028 can be simplified by just using the `RSQLUtility#isValid` method directly within `RsqlParserValidationOracle`. It would allow to get rid of the database call and make sure the query is eligible for `RsqlParser` without using the `TargetManagement` at all. But after taking a closer look at it, I saw that it does not take into account allowed RSQL fields (see [TargetFields](https://github.com/eclipse/hawkbit/blob/master/hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/TargetFields.java)). As a result the method is only validating the syntax but ignores the supported fields of a Target (e.g. `a==b` would be valid, however the resulting SQL query would be targeting unknown fields causing SQL Exception later on).

Having this said I would propose to go for something like this:
- Extend the `RSQLUtility#isValid` method to include the `FieldNameProvider` and `VirtualPropertyReplacer` into validation similar to already existing
```
RSQLUtility.parse(query, TargetFields.class, virtualPropertyReplacer, database);
```
- In order to achieve this I would suggest taking a look at `RSQLSpecification#toPredicate` method and potentially introduce own `RSQLVisitor<Boolean, String>` which is independent from `JpqQueryRSQLVisitor` and does not use the JPA Specification API. It should just include the parts of `JpqQueryRSQLVisitor` that verify the validity of RSQL query:
```
public Boolen visit(final ComparisonNode node, final String param) {
    try {
        final A fieldName = getFieldEnumByName(node);
        getAndValidatePropertyFieldName(fieldName, node);
    } catch (final IllegalArgumentException e) {
        return false;
    }
    return true;
```

**Comment by Sergey-G-dev** [comment]
Thanks a lot for the feedback @bogdan-bondar! I didn't realize that `TargetFields` are taken in consideration when validating the query text field. Your suggestion sounds plausible, I'll add `TargetFields` to validation process and prepare a new PR.

**Comment by Sergey-G-dev** [comment]
I've prepared a new draft PR (https://github.com/eclipse/hawkbit/pull/1040) where I added the allowed `TargetFields` into validation.

I've followed the idea suggested by @bogdan-bondar by implementing a custom `RSQLVisitor` which throws an `RSQLParameterUnsupportedFieldException` if a RSQL key is not valid as defined by `TargefFields.class`.

I had to copy/paste some private utility methods from `JpqQueryRSQLVisitor` since they serve the same purpose. Which is not optimal because of the violation of DRY principle.

There is no need to involve `VirtualPropertyReplacer` into validation because all it does is replacing placeholder like `${now_ts}` and `{overdue_ts}` in values by a `Long` value representing Unix epoch time, The RSQL values are not subject to validation, they can be any random string.

Please review, comment, share feedback. Thanks!
