### ISSUE TITLE
Using NATS instead of RabbitMQ

### ISSUE THREAD

**Issue by lab-w** [eclipse/hawkbit#1041]
Is it easily possible to use NATS messaging instead of RabbitMQ? I'm asking for a project where NATS is used anyway and RabbitMQ would mean to have another simmilar infrastructure in parallel.

Thanks for any hints or comments!

**Comment by schabdo** [comment]
I'm not deep into NATS but RabbitMQ is mainly used by the DMF API (Device Management Federation) as a communication vehicle in order to connect devices with different protocols (other than HTTP) or even full blown device management applications. So if you'd like to stick to DMF API I'd rather assume that it's not easily possible since you need to introduce some kind of abstraction layer within the DMF code to either use NATS or RabbitMQ. The easier way would be to put NATS next to DMF as a completely new integration point and basically do same as DMF but backed by NATS

**Comment by lab-w** [comment]
Thanks a lot @schabdo . This outlines the options. I probably will stay with the RabbitMQ implementation.
