### ISSUE TITLE
JPA Repository broken with SQLServer after Eclipselink update

### ISSUE THREAD

**Issue by kaizimmerm** [eclipse/hawkbit#1045]
Hi,

the recent Eclipselink upgrade from #1038 unfortunately broke the SQLServer support.

It causes massive exceptions `com.microsoft.sqlserver.jdbc.SQLServerException: ORDER BY items must appear in the select list if SELECT DISTINCT is specified.`

The reason is the change introduced with https://github.com/eclipse-ee4j/eclipselink/pull/300 which causes the error. 

I am open for suggestions. We either drop SQLServer support or revert the Eclipselink upgrade.

I reported this in Eclipselink as well https://github.com/eclipse-ee4j/eclipselink/issues/963

Kai

CC: @schabdo

**Comment by schabdo** [comment]
As far as I was able to track down the changes for SQL Server it seems that changes went straight into EclipseLink `2.7.4`.

> We either drop SQLServer support or revert the Eclipselink upgrade 

Since we do not enforce Java 11 yet and there is still some way to go (e.g. official release, ...) I'd suggest to go for the latter option and downgrade EclipseLink for now. Furthermore there is already a fix (thanks a lot by the way!) handed-in to EclipseLink so it could be fixed in the meanwhile till we're good to go for Java 11

**Comment by kaizimmerm** [comment]
Agree, did that already in #1047
