### ISSUE TITLE
Automatic device registration

### ISSUE THREAD

**Issue by eschenbachertq** [eclipse/hawkbit#1088]
Hi,

we would like to integrate hawkBit for remote updates into our existing product in the future. Now we ask ourselves whether there is a concept for the automatic registration of devices?

Background:
We have many existing devices in the field. We cannot or do not want to enter these devices into the hawkBit system manually via the Management UI or the Management API. Instead, a kind of registration process would be helpful, in which a previously unknown device reports to the hawkBit server.
In addition, it should be possible to transfer metadata such as serial number and MAC address etc., on the basis of which the hawkBit server can decide whether to register the device or not.

Is there already a concept for such an application? How do other manufacturers deal with it if they want to integrate hawkBit into devices that have already been rolled out?

Many thanks!

**Comment by schabdo** [comment]
Glad to hear that you're considering hawkBit for software updates in your solution! According to your explanation the [DMF API](https://www.eclipse.org/hawkbit/apis/dmf_api) sounds like a good fit. This API is message based and explicitly designed for integration with already existing 3rd-party device management solutions where hawkBit is only responsible for the software update part. DMF supports automatic device registration as well.

> In addition, it should be possible to transfer metadata such as serial number and MAC address

Supported by DMF via `UPDATE_ATTRIBUTES` message

> [...] on the basis of which the hawkBit server can decide whether to register the device or not

I think this should be rather part of your solution since how hawkBit should know whether or not the device should be ignored when you send the `THING_CREATED` message?

> How do other manufacturers deal with it if they want to integrate hawkBit into devices that have already been rolled out?

I know that some of them compile a plain list from the factory and pre-provision them within hawkBit (either via CSV upload or by using management API) and others do use the automatic registration of devices based on client certificates (this is a feature of DDI API). However this feature would require a reverse-proxy in front of hawkBit that is terminating the SSL/TLS connection and extracts the certificate information in order to allow hawkBit to verify whether or not access for this device should be granted.

Hope this helps to get you started!
