### ISSUE TITLE
Cannot get hawkBit's version number from any of its APIs

### ISSUE THREAD

**Issue by volphy** [eclipse/hawkbit#1133]
Neither of the available hawkBit API's:

- https://www.eclipse.org/hawkbit/apis/management_api/
- https://www.eclipse.org/hawkbit/apis/ddi_api/
- https://www.eclipse.org/hawkbit/apis/dmf_api/

provides a way to enquire that a given hawkBit Update Server's instance is running a specific version of the hawkBit (e.g. 0.3.0M7).

Is it a conscious design choice or omission?

**Comment by bogdan-bondar** [comment]
Hi @volphy there is indeed no such API. Currently `project.version` from maven is mapped to `hawkbit.server.build.version` available in code under `HawkbitServerProperties`. May I ask you why you need to retrieve project version via API?

**Comment by volphy** [comment]
Short answer: CI/CD workflow.

Long answer:
We have updated the hawkBit from 0.3.0M6 to 0.3.0M7 in our infrastructure.

It seemed to be not obvious how to verify that a remote hawkBit instance (running in the AWS ECS) is actually running the newer hawkBit's version (here: milestone).

As an ugly hack, we did `docker save <our_private_docker_registry>/hawkbit:0.3.0M7 > hawkbit.tar` and inspected all layers of the Docker image compressed to a single tar file.

**Comment by bogdan-bondar** [comment]
In your case I would just rely on docker image tag, sorry, but I still don't see the reason not to trust it leave alone trying to inspect the tar archive.
Nevertheless if you really need that info exposed, I would suggest adding it to the `info` section of spring boot actuator: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.info
In order to accomplish it you would need to:
1) Add `<artifactId>spring-boot-starter-actuator</artifactId>` dependency to hawkbit update server pom
2) In the same pom add `<filtering>true</filtering>` under `build->resources->resource`
3) Add `info.app.version=@project.version@` to `application.properties`
After doing it you will see the version under `http://<url>/actuator/info` endpoint
Hope this helps

**Comment by volphy** [comment]
Thanks for clarification
