### ISSUE TITLE
Trigger rollout groups manually in large rollouts

### ISSUE THREAD

**Issue by krishna-devolo** [eclipse/hawkbit#1208]
When running a rollout with high number of targets, say over 300K, it takes a substantial amount of time for one rollout group to reach the trigger threshold. In some scenarios, we know that the trigger threshold *will eventually be reached*. We nevertheless have to wait for this happen before the next rollout group begins. 

An option to manually trigger the next rollout group in such scenarios will speed up the overall rollout progress.

**Comment by bogdan-bondar** [comment]
Hi! Sorry, but I don't get your intention here... The Trigger threshold is the percentage of targets in the group, that must be successful before the next group is started. This can be seen as a security mechanism and load distribution together with Error threshold. 
Could you elaborate how would you "know that the trigger threshold will eventually be reached"? You can't predict the behaviour of devices and their polling/feedback distribution. 
Could you describe your use-case in more details, because currently you could achieve similar behaviour by just setting the trigger threshold to 0/low value?
