### ISSUE TITLE
Can't deploymentBase href in Hawkbit docker container

### ISSUE THREAD

**Issue by PagnuM** [eclipse/hawkbit#1367]
Hello, I'm currently trying to run the Hawkbit docker on ECS and CloudFront with HTTP to HTTPS redirection, so the setup would be:  CloudFront -> Application Load Balancer -> Container.

Connecting to the  Management interface through a browser is no problem, and using a Hawkbit client (rauc-hawkbit-updater) when there are no updates is no problem either, but when the client gets an update the response body contains the artifact URL but with the HTTP protocol, not the HTTPS protocol:
```
"deploymentBase" : {
     "href" : "http://...."
}
```

I have tried setting the following properties to no avail:
```
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    environment:
      SPRING_APPLICATION_JSON: '{
        "hawkbit.artifact.url.protocols.download-http.protocol": "https",
        "hawkbit.artifact.url.protocols.download-http.port": "443"
      }'
```

Even if I change the "hawkbit.artifact.url.protocols.https.ref" to whatever it doesn't change anything. In the client all I get is a "HTTP request failed: 301" with a server response from CloudFront that says "301 Moved Permanently", I thing it's because when connecting using HTTPS CloudFront connects to the container using HTTP but I'm not sure.  

Thank you all in advance.

**Comment by strailov** [comment]
Hello @PagnuM  ! 
Thanks for posting this issue ! 
Can you provide the request that you are making ? And also the output seems to be not structured right if I am understanding correctly what you are doing. I assume you use [this](https://www.eclipse.org/hawkbit/rest-api/rootcontroller-api-guide.html#_get_tenantcontrollerv1controlleriddeploymentbaseactionid) ? There is an example response as you can see in the link, so there should be https link present even if you don't change anything in the configuration I suppose.

**Comment by PagnuM** [comment]
I've solved the issue, the Hawkbit client I was using wasn't following the redirect, so as soon as I enabled that FLAG that got rid of the problem. Although I was still passing the Authorization header via HTTP so anyone in the network could see it, so I changed the client's code to replace "http://" with "https://" to avoid the redirect, quite a hacky way to do things but it did the trick.

I'll close the issue now, I think there should be a property to make Hawkbit believe it's using SSL so that all links in the response body come out with HTTPS to adapt better to cases like mine where I'm running Hawkbit behind a Load Balancer behind CloudFront.

**Comment by marcusx** [comment]
@PagnuM I had the exact same problem with the same stack. AWS ECS using Fargate for running the Hawkbit container behind an Application Load Ballancer that terminates the SSL.

The problem is that Hawkbit with default settings ignores the X-Forward-Prot Header from the ALB. Therefore spring boot is not generating the correct protocol in absolute URLs it sends back in responses.

You have to set `SERVER_FORWARD-HEADERS-STRATEGY=NATIVE` as an environment setting.

Like this in the ECS task definition.

           {
             name  = "SERVER_FORWARD-HEADERS-STRATEGY"
             value = "NATIVE"
           },
        
Got this from the sandbox setup in the hawkbit repo. There is nginx is used as a proxy instead of ALB but the same principle.
See this commit where the setting was changed a while ago due to spring boot changes. 
https://github.com/eclipse/hawkbit/commit/1d4ffa7604518c7aaff47a7b39bba6387cd7b17b

For reference also the complete settings you can find here:
https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties

If you want to overwrite spring boot properties in environment vars you need to replace dots with underscores and uppercase the stuff.

See this explanation of what happens if you are not into spring boot. https://tomgregory.com/spring-boot-behind-load-balancer-using-x-forwarded-headers/

Hope this helps to get this working without redirecting.

**Comment by daa** [comment]
Should note that for 0.3.0M9 native forward headers strategy didn't work for me and I had to use server.forward-header-strategy=FRAMEWORK.

**Comment by avgustinmm** [comment]
@daa, 
maybe this PR (merged in master, not released yet) would make NATIVE work - https://github.com/eclipse/hawkbit/pull/1449
