### ISSUE TITLE
Hawkbit Documentation is Unavailable

### ISSUE THREAD

**Issue by nealjack** [eclipse/hawkbit#1387]
All links to the documentation on github and the example UI currently redirect to an out of date [site](https://projects.eclipse.org/projects/iot.hawkbit) from 2018.

Is there a new location for the documentation?

**Comment by strailov** [comment]
Hey @nealjack ! 
Yeah, it seems there is something wrong... I'll check this.

**Comment by strailov** [comment]
Hey @nealjack  ! 
Seems that currently there is some issue with eclipse... I have created an issue there -> https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3365

**Comment by strailov** [comment]
Hey @nealjack ! 

The documentation seems to be available now -> https://eclipse.dev/hawkbit/

**Comment by marcusx** [comment]
You can open the API docs directly without the iframes. e.g: https://eclipse.dev/hawkbit/rest-api/rootcontroller-api-guide.html#_get_tenantcontrollerv1controlleriddeploymentbaseactionid

**Comment by strailov** [comment]
Yes indeed ... 
It was related to some domain migrations of eclipse, still working on it, but mainly the documentation should work now and most importantly the api links.

**Comment by strailov** [comment]
I think it is all okay now, at least on my side everything seems to work fine.

**Comment by nealjack** [comment]
Yes, it is working now for me too!

**Comment by nealjack** [comment]
It appears there are still sections of the documentation that are broken, notably the rest api documents.

This page is empty:
https://eclipse.dev/hawkbit/rest-api/

This page is a 404:
https://eclipse.dev/hawkbit/rest-api/targettag-api-guide.html

Do these pages exist elsewhere? These links are still listed on google, which is confusing.

**Comment by avgustinmm** [comment]
Hi, 
there is a change how the REST API documentation is build. Now, hawkBit supports swagger & openapi and the documentation is build with redoc based on the openapi descriptions. This leads to different documentation format on the site.
You could find the REST API doc as usual at https://eclipse.dev/hawkbit/apis/.
Specifically targettag api is at https://eclipse.dev/hawkbit/apis/management_api/.
It's confusing if google keeps outdated links but we couldn't keep structure of the site static forever just because of google. I hope soon google will "find out" there are. no such pages and will stop offering them.
If you feel there is still a problem with hawkBit site please open new issue.

**Comment by nealjack** [comment]
Thanks for linking the documentation.

This page is still a valid page, but doesn't link anywhere:
https://eclipse.dev/hawkbit/rest-api/

You may want to remove it or have it redirect to the actual documentation
