### ISSUE TITLE
Rest end Point "http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.key/" is not Fetching the Gateway Token.

### ISSUE THREAD

**Issue by PrabhjeetSingh90** [eclipse/hawkbit#1410]
I have enabled the gateway Token in the Hawkbit Server using the Below REST API
curl --user admin:admin   -X PUT -H 'Content-Type: application/json' -i 'http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.enabled/' --data '{  "value": true } '

**Here is the Output**
HTTP/1.1 200 OK
Date: Wed, 02 Aug 2023 06:53:29 GMT
Content-Type: application/hal+json;charset=utf-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 241
 
{"value":true,"lastModifiedAt":1690959209692,"lastModifiedBy":"admin","createdAt":1690959209692,"createdBy":"admin","global":false,"_links":{"self":{"href":"http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.enabled"}}}

However When I am trying to Read the Gateway Token using below API , Its showing the Blank value

 curl --user admin:admin -X GET -i 'http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.key/'

Here is the Response.

{"value":"","lastModifiedAt":1690959620059,"lastModifiedBy":"admin","createdAt":1690959620059,"createdBy":"admin","global":false,"_links":{"self":{"href":"http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.key"}}}

Few Questions:
1) Why we are not able to read the generated token using REST end Point "'http://localhost:8080/rest/v1/system/configs/authentication.gatewaytoken.key/" ?

2) If I open up the UI and manually enable the Hawkbit Server to generate Authentication Token and then save it. I am able to read that Token from same REST end point shown above?

**Comment by avgustinmm** [comment]
Hi @PrabhjeetSingh90, 
thanks for you interest in hawkBit. 

Actually setting gateway token enabled doesn't set any real token. It just sets a configuration property. 
It might even be dangerous because, I suppose that, if a token is assumed empty string than maybe your system will accept empty string as a token!

In order to actually enable gateway token authentication you should:
1. generate a secret by yourself
2. set it as a token (first!)
3. just after you have set token (and not empty string is returned) you should enable gateway token authentication

When you just enable gateway token authentication via rest and go to UI you could see tokens - but they are generated by UI and not really read from database. If you switch selection few times you'll see the token is changed - it is regenerated each time.
If now you save config - UI will save generated token and then you could read it via REST API.

If you enable gateway token authentication via UI - then it does both - enable & set generated token. That's why you could get it via REST API.

**Comment by PrabhjeetSingh90** [comment]
Thank you @avgustinmm for the clarification. 

I am doing some sort of automation where I do not want to keep any manual step in updating the token on the UI.

Are you aware of any rest endpoint that will help us in set the secret token in the Hawkbit Server ? 

OR

Is there a way to enter this secret token while starting or installing the Hawkbit Server ?

I am asking this because I do not want to manually go to the UI and update the token.  I am looking for steps which I can use to automate. Maybe some Rest API or some file update in the Docker Container.

**Comment by PrabhjeetSingh90** [comment]
Thank you again @avgustinmm for you help

I was able to set the token using DDI API while starting the container as shown below. Now I can fetch the token anytime using REST API's

sudo docker run -p 8080:8080 hawkbit/hawkbit-update-server:latest --hawkbit.server.ddi.security.authentication.gatewaytoken.enabled=true --hawkbit.server.ddi.security.authentication.gatewaytoken.key="04692bf008d5a9a6a0f78d
ffcb84b200"
