### ISSUE TITLE
Abrupt exit of hawkbit container with MySQL instance after run

### ISSUE THREAD

**Issue by prawin-srini** [eclipse/hawkbit#1682]
I am trying to build the HawkBit docker container with MySQL support following the instructions on the README.  Build logs in : 
[Build_log.txt](https://github.com/eclipse/hawkbit/files/14539596/Build_log.txt) I've modified the Dockerfile as I faced build issues with copying with a multi-stage build and outdated reference for the MariaDB connector. As found in [Dockerfile-mysql.txt](https://github.com/eclipse/hawkbit/files/14539746/Dockerfile-mysql.txt)
At the moment I have not made any changes therefore have not used the development image only wanted to test if the server  runs on my localhost 8080 with a mysql backend instance. However I encounter into the following issue when running the docker container where it stops abruptly. 
$docker run -d -p 8080:8080 hawkbit_update_server:0.4.1-mysql
5ee3f869a84d8f0b96326487073ef136c38b920eca3a2f2b11fee9a8c006d3bd
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ docker logs 5ee3f869a84d8f0b96326487073ef136c38b920eca3a2f2b11fee9a8c006d3bd
Error: Could not find or load main class org.springframework.boot.loader.launch.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.launch.JarLauncher
I referred to an existing open issue which is quite similar to what I am trying to do [Issue:1494](https://github.com/eclipse/hawkbit/issues/1494)
I also verified that the RabbitMQ and MYSQL service instances are running in the background.  However, the issue seems to be related in the way the Spring boot application has been packaged.  Are there any solutions to resolve this issue?

**Comment by avgustinmm** [comment]
Hi @prawin-srini , 
there is a big change in the master compared to 0.4.1. The 0.4.1 uses Spring Boot 2.7 while the master is already migrated to Spring Boot 3. 
Spring Boot changed the package of their launcher class JarLauncher from org.springframework.boot.loader to org.springframework.boot.loader.**launch**. Thus why the Dockerfiles from the master are not compatible with 0.4.1.

So, in order to build docker files for 0.4.1 you have 2 options:
1. Checkout 0.4.1 tag and build images with its Dockerfiles
2. Manually edit master's Dockerfiles and change the launcher package to the Spring Boot 2.7 one - org.springframework.boot.loader.JarLauncher
