### ISSUE TITLE
Hawkbit docker reboot while retaining previous device data

### ISSUE THREAD

**Issue by SatriaPriambada** [eclipse/hawkbit#1722]
Hi Hawkbit devs,

I'm exploring hawkbit as a way to do update on my embedded software. Thanks for all your hard work! so far it works great for me
I'm opening issue to ask a question about is there a way for hawkbit docker reboot while retaining previous device data

Every time I shut down my docker, I seems to lost all my target_devices
I need to create new device, add the devices again, then update the software
I don't want to run the docker all the time and only spawn it when I need it because the software update is only for <5 devices that happens every couple months 

Thanks and have a great day!

**Comment by avgustinmm** [comment]
Hi @SatriaPriambada, 
thanks for your interest in hawkBit. 
Docker images and compose files are just examples of how hawkBit could be containerized. They are not intended for any real usage. That's why MySQL is set without persistent volume. 
If you want your devices to survive a restart you should modify the hawkBit compose files accordingly - you should make MySQL use persistent volume. 
PS: As noted in "Ask a question" section at https://eclipse.dev/hawkbit/community, in future, please ask questions in StackOverflow
