### ISSUE TITLE
Prevent devices from self-creating

### ISSUE THREAD

**Issue by lizziemac** [eclipse/hawkbit#1842]
Hi there! Is there a way to prevent devices from self-creating themselves upon connecting to hawkBit? I looked at the management UI settings (still on 0.3.0), and it doesn't look like it.  I'm having issues where sometimes the devices create themselves in hawkBit before I bulk create them via my backend, resulting in 409s.

My current workaround is checking if there is a 409, deleting each registered but non-configured device, and then re-creating, but ideally I'd like to prevent this situation altogether.

Thanks!

**Comment by avgustinmm** [comment]
I think it is not possible even in the newest version. If the device has been successfully authenticated it is created.
You will get this "prevent" effect only if you're using target secret authentication I suppose - then the device won't be able to authenticate because its secret won't be available on the server side.
