### ISSUE TITLE
What is the main goal of the tenant

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#379]
Hi,
I read the DDI API and there are two questions open

1. What is the main goal of the tenant. Currently only DEFAULT works ??
GET /{tenant}/controller/v1/{controllerId}

2. What is the best way to realize DDI API with multi devices behind one Device?

[Dev 1 Master with WEB Connection]
+--<user protocol>--- [Dev 1.1]
+--<user protocol>--- [Dev 1.2]
+--<user protocol>--- [Dev 1.3]

**Comment by kaizimmerm** [comment]
hawkBit is prepared to be run as multi tenant system. However, you need an authentication service that supports multiple tenants and users. We are using a proprietary system over here but @michahirsch has provided an [example based on the UAA project as well](https://github.com/eclipse/hawkbit/tree/master/extensions/hawkbit-extension-uaa).

Concerning your other question. 

You have two options I think:

1. Run your master as hawkBit (provisioning) target. The others are modelled only in the DistributionSet if necessary (i.e. Software Module types per sub device category). Lets assume your Dev 1.1 and 1.2 are of the same hardware type and 1.3 of another . Then you would define two software module types "Firmware for 1.1-2 devices and "Firmware for 1.3 devices" You client than knows which module belongs where. hawkBit makes no distinction between the devices, its just one big "virtual" device. This scenario is btw. the reason why we call this entity (provisioning) _target_ and not _device_.
2. The other option is of course that your master calls hawkBit per device and as a result hawkBit is aware of all of them and treats all of them as individual target.

In both scenarios hawkBit is actually not really aware of the topology. By design hawkBit does not care.

**Comment by EugenWiens** [comment]
Thank you @kaizimmerm for the information. I will play around and my by I will come back with more questions regarding the Software Modules.

**Comment by kaizimmerm** [comment]
You are welcome.
