### ISSUE TITLE
The Download link for the artifacts is not switching to hawkbit.url

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#385]
I have set the setting hawkbit.url in the application.properties but when I perform a GET to the deploymentBase/ID/ URL the response is wrong. For the download link hawkBit returns localhost:8080...

            "_links": {
              "download-http": {
                "href":  "http://localhost:8080/DEFAULT/controller/v1/eugenId/softwaremodules/2/artifacts/fimware.txt"
              },
              "md5sum-http": {
                "href": "http://localhost:8080/DEFAULT/controller/v1/eugenId/softwaremodules/2/artifacts/fimware.txt.MD5SUM"
              }
            }

**Comment by michahirsch** [comment]
hawkBit supports to generate download-links to other hostsnames, because you might want to download from other server than hawkBit itself.

So you can checkout the properties in the https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/resources/hawkbitdefaults.properties there you can see 
```
hawkbit.artifact.url.protocols.download-http.hostname=localhost
hawkbit.artifact.url.protocols.download-http.port=8080
hawkbit.artifact.url.protocols.download-http.ref={protocol}://{hostname}:{port}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}
```

**Comment by EugenWiens** [comment]
Now it works.
You right thank you for the help.

**Comment by michahirsch** [comment]
You're welcome, thanks.
