### ISSUE TITLE
Change UI demo account setting does not work

### ISSUE THREAD

**Issue by embeddedgeeks** [eclipse/hawkbit#457]
change UI demo account settings does not work:

examples/hawkbit-example-app/src/main/resources/application.properties

# UI demo account
hawkbit.server.ui.demo.password=admin123
hawkbit.server.ui.demo.user=admin
hawkbit.server.ui.demo.tenant=SOMETENANT

**Comment by michahirsch** [comment]
Hi,

this is a little bit misleading, because the demo-account is used to automatically login to hawkBit by clicking the demo button. See the sandbox login dialog https://hawkbit.eu-gb.mybluemix.net/.

If you want to change the login username and password you need to change the following properties
```
# User Security
security.user.name=admin
security.user.password=admin
```

The tenant will also be `DEFAULT`

Cheers,
Michael

**Comment by embeddedgeeks** [comment]
Hi,
thanks for the quick answer!
It means  it's not possible to customize the Tenant ?

Cheers

**Comment by michahirsch** [comment]
No the tenant is not configurable in the default in-memory user management, see https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/java/org/eclipse/hawkbit/autoconfigure/security/InMemoryUserManagementAutoConfiguration.java

So without coding you are not able to set the tenant.

We could introduce a property for that to set the tenant as well.

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
