### ISSUE TITLE
Artifact file not available at download-http

### ISSUE THREAD

**Issue by voltatindell** [eclipse/hawkbit#497]
I am trying to get hawkBit running with SWUpdate and want to support updates of >1GB.  Uploading an .swu file that large required changing the max-file-size consts from 1024MB to 4096MB.  The Suricatta daemon/hawkBit exchange proceeded as expected until curl made a GET request for the file using the download-http in previously requested JSON; the response comes back with a 406 NOT_ACCEPTED error.  The "downloaded <nnnn> bytes" log message in channel_get_file() reports 0 bytes downloaded.  Trying the download-http URL in my browser reports file not found.

When I use 'head -c 777777777' to lop off part of the .swu file to make it <1GB, upload it to hawkBit,  and repeat forcing the update, all is well and the file is downloaded by channel_get_file().  As expected because of file breakage, it fails (HASH mismatch).  Browsing to the download-http causes UI to ask if I want to download the 777777777 byte file.

Would anyone be kind enough to shed a little light on this for me?  Are there other consts I need to change in hawkBit to get it working with .swu >1GB?  Thanks in advance.

--Mike Tindell .  www.voltacharging.com

**Comment by michahirsch** [comment]
Hi @voltatindell,

I just tried it locally to upload a 1,5GB file to hawkBit and downloaded via curl and it worked for me.

```
$ curl http://localhost:8080/DEFAULT/controller/v1/large/softwaremodules/1/artifacts/largefile.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1536M  100 1536M    0     0  6716k      0  0:03:54  0:03:54 --:--:-- 7133k
```

As you mentioned to be able to upload files larger than 1GB you'll need to configure the property `max-file-size` there is also a `max-request-size` but this is set to `infinite` in hawkBit `spring.http.multipart.max-request-size=-1` 

Can you provide me a hawkBit debug log-file which shows the 406 HTTP error? 
You can set the log-level in hawkBit by either modifying the 
`src/main/resources/logback-spring.xml` e.g. `<Root level="DEBUG">`

or 

you providing the logging-properties via environment variable `LOGGING_LEVEL_ROOT=DEBUG`

Cheers,
Michael

**Comment by voltatindell** [comment]
Here are two swupdate log files for the two cases I mentioned: big (~1.5GB .swu) and small (777GB file, previous one whacked in half).  I had set loglevel to 5 on the command line.  I will generate the hawkBit logs momentarily.

[big.txt](https://github.com/eclipse/hawkbit/files/962213/big.txt)
[small.txt](https://github.com/eclipse/hawkbit/files/962214/small.txt)

**Comment by sbabic** [comment]
Hi,

On 27/04/2017 18:26, voltatindell wrote:
> Here are two swupdate log files for the two cases I mentioned: big
> (~1.5GB .swu) and small (777GB file, previous one whacked in half). I
> had set loglevel to 5 on the command line. I will generate the hawkBit
> logs momentarily.
> 

I guess Michael wants to see the Hawkbit's log, not SWUpdate's.

> big.txt <https://github.com/eclipse/hawkbit/files/962213/big.txt>
> small.txt <https://github.com/eclipse/hawkbit/files/962214/small.txt>
> 

Firstly, I want to state that very big files are not so common. At
least, not (yet) in my projects. Even if a .swu of several hundreds MB
is not so unusual, a size > 1GB is quite an exception. This is just to
say that the bug could be in SWUpdate and not in Hawkbit.

Anyway, checking "big.txt", I see what you have already reported:

> GET
/DEFAULT/controller/v1/11/softwaremodules/1/artifacts/volta_1.0.swu HTTP/1.1
User-Agent: libcurl-agent/1.0
Host: localhost:8080
Content-Type: application/octet-stream
Accept: application/octet-stream

< HTTP/1.1 406 Not Acceptable
< Content-Disposition: attachment;filename=volta_1.0.swu
< ETag: 55bfbafb2f9b95fa0e5378718bb8f0f97947c4f7
< Accept-Ranges: bytes
< Content-Range: bytes 0-1557360639/1557360640
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Cache-Control: must-revalidate,no-cache,no-store
< Connection: close
<
* Closing connection 0

This is the debug output of the libcurl library. It is just a GET to the
URL provided by Hawkbit. Because the get returns HTTP=406, SWUpdate does
not go on with the update. The "Channel downloaded 0 bytes ~ 0 MiB" is
just because the update was stopped before starting, and no data was
processed. So at first glance, it looks that the server refuses to make
the image available when it exceeds a limit.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by voltatindell** [comment]
That is how it appears: the small (<1GB) file is available at the http-download URL, while the large file is not available at its URL.  Thanks for helping me out with this, guys!  I'm generating the hawkBit logs now and will upload after I look at them.

**Comment by voltatindell** [comment]
Setting log level to DEBUG produced several GB of logging that was impractical.  I uploaded two logs made at INFO level for big and small files.  UI indicated both uploads succeeded.  In both cases I tried accessing:

     http://localhost:8080/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/[small, big].swu

Only in the small.swu case did a servlet handler note the attempted get; big.swu only occurs in big.log for upload progress updates.

[big.txt](https://github.com/eclipse/hawkbit/files/962838/big.txt)
[small.txt](https://github.com/eclipse/hawkbit/files/962837/small.txt)

I could try squeezing my gzipped update under a GB, but it seems like this should be working.  I have not used Java in 20 years, so Spring isn't familiar at all to me.  I don't know where to begin debugging the HTTP request handling.  I can see about exposing a URL for my hawkBit, but it seems like I am following directions for doing the upload.

Given that the URL for the large artifact is not being served by hawkBit, it would seem the issue is not with SWUpdate.

I would **really** like to use hawkBit rather than writing my own server to use with Suricatta.  Even if I can get my image whittled down in size (it includes a .NET media player app that uses the Mono layer, and a few other applications), it would be nice to do updates of any size (this is for an out-of-home media kiosk).

Thanks again,
--Mike

**Comment by sbabic** [comment]
Hi Mike,

On 27/04/2017 22:38, voltatindell wrote:
> Setting log level to DEBUG produced several GB of logging that was
> impractical. I uploaded two logs made at INFO level for big and small
> files. UI indicated both uploads succeeded. In both cases I tried accessing:
> 
> |http://localhost:8080/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/[small,
> big].swu |
> 
> Only in the small.swu case did a servlet handler note the attempted get;
> big.swu only occurs in big.log for upload progress updates.
> 
> big.txt <https://github.com/eclipse/hawkbit/files/962838/big.txt>
> small.txt <https://github.com/eclipse/hawkbit/files/962837/small.txt>
> 

I can just say that I do not have on my setup:

org.springframework.amqp.AmqpConnectException:
java.net.ConnectException: Connection refused (Connection refused)

I do not know if this a reson, but it looks like that the rabbitMQ
configuration is not ok.

> I could try squeezing my gzipped update under a GB, but it seems like
> this should be working. I have not used Java in 20 years, so Spring
> isn't familiar at all to me. I don't know where to begin debugging the
> HTTP request handling. I can see about exposing a URL for my hawkBit,
> but it seems like I am following directions for doing the upload.
> 
> Given that the URL for the large artifact is not being served by
> hawkBit, it would seem the issue is not with SWUpdate.

ok - nice to know.

> 
> I would *really* like to use hawkBit rather than writing my own server
> to use with Suricatta.

Well, this does not seem at the moment a great idea if the only reason
is to fix an issue. The issue should just be investigated and fixed -
from you or you contract someone if you cannot go on from this
discussion. But I do not expect this is a blocking point to use Hawkbit.

A new backend in suricatta (the daemon in SWUpdate to communicate to a
back end, as we are discussing at Hawkbit's home and some terms are
strange here) requires surely a much higher effort as to fix this issue.
Not to mention the long list of new issues because everything is new.

And if your server is under a closed license, your changes to SWUpdate
will not merged and you are constrained to run your own thing - also a
bad idea.

> Even if I can get my image whittled down in size
> (it includes a .NET media player app that uses the Mono layer, and a few
> other applications), it would be nice to do updates of any size

Right - I see the same. Anyway, I cannot say that it is already clear
where is the cause. We can still have :

- the bug is in Hawkbit - it must be fixed here
- the bug in SWUpdate (less probable from your report)
- the bug is ny your configuration for Hawkbit and not in Hawkbit's code

> (this is
> for an out-of-home media kiosk).
> 

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment]
Hi,

@sbabic thanks a lot for clarification and for the help.

@voltatindell thanks for the detailed information. I know that the `DEBUG` log is quiet intense but didn't know that it will give you several GB :). Would you mind to try to reproduce the issue with the log-configuration like:

`LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG` 
or in the `logback-spring.xml` `<Root level="INFO">` but `<logger name="org.springframework.web" level="DEBUG" />` this should produce less logs but maybe enough to see something. That would be awesome, thanks.

Additional I'll keep trying to break it down to the hawkBit issue. Due `SWUpdate` retrieves the 406 HTTP error from hawkBit I would guess it is a hawkBit issue otherwise `SWUpdate` would not retrieve this error. 

My first test was with an 1.5GB file created by windows using `fsutil` to generate a file with the length. Maybe I need to take a real file that size for testing. 

@sbabic I guess testing with a big file size and using a normal `curl` would be sufficient, right? `SWUpdate` is also just doing a `curl` command.

Cheers,
Michael

**Comment by sbabic** [comment]
Hi Michael,

On 28/04/2017 15:06, Michael Hirsch wrote:
> Hi,
> 
> @sbabic <https://github.com/sbabic> thanks a lot for clarification and
> for the help.
> 
> @voltatindell <https://github.com/voltatindell> thanks for the detailed
> information. I know that the |DEBUG| log is quiet intense but didn't
> know that it will give you several GB :). Would you mind to try to
> reproduce the issue with the log-configuration like:
> 
> |LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG|
> or in the |logback-spring.xml| |<Root level="INFO">| but |<logger
> name="org.springframework.web" level="DEBUG" />| this should produce
> less logs but maybe enough to see something. That would be awesome, thanks.
> 
> Additional I'll keep trying to break it down to the hawkBit issue. Due
> |SWUpdate| retrieves the 406 HTTP error from hawkBit I would guess it is
> a hawkBit issue otherwise |SWUpdate| would not retrieve this error.

Right.

> 
> My first test was with an 1.5GB file created by windows using |fsutil|
> to generate a file with the length. Maybe I need to take a real file
> that size for testing.
> 
> @sbabic <https://github.com/sbabic> I guess testing with a big file size
> and using a normal |curl| would be sufficient, right? |SWUpdate| is also
> just doing a |curl| command.

I think yes - SWUpdate does not exec curl, but it is linked against
libcurl - what the "curl" command also uses.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by voltatindell** [comment]
To amplify, procedure works with file <1GB, same sw-description, all is
well until hash mismatch, which is to be expected since I slice the .xwu
file in half.  With >1G file, hawkBit does not serve the file at
http-fownload URL on localhost and update aborts because no bytes were able
to be read.   Same process of upload, define sw module, define
distribution, add module to distribution, drag distribution onto target, id
done in cases of small and big files, just different behavior as results.

As an aside, I have a minimal rootfs.swu and that deploys fine.

Cheers,
--Mike

**Comment by voltatindell** [comment]
Michael, changing the log level as you described added this to the logging output:

2017-04-28 16:47:27.171 DEBUG 671 --- [tp1648582256-16] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/big.swu]
2017-04-28 16:47:27.173 DEBUG 671 --- [tp1648582256-16] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /DEFAULT/controller/v1/1/softwaremodules/1/artifacts/big.swu
2017-04-28 16:47:27.183 DEBUG 671 --- [tp1648582256-16] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public org.springframework.http.ResponseEntity<java.io.InputStream> org.eclipse.hawkbit.ddi.rest.resource.DdiRootController.downloadArtifact(java.lang.String,java.lang.String,java.lang.Long,java.lang.String)]
2017-04-28 16:47:27.190 DEBUG 671 --- [tp1648582256-16] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/big.swu] is: -1

[big.txt](https://github.com/eclipse/hawkbit/files/965768/big.txt)

I'll set up an EC2 instance with the code and see if I still see the problem; that way, you can, too. ;)

Thanks,
--Mike

**Comment by voltatindell** [comment]
I have hawkBit running in an EC2 instance at http://54.187.2.152:8080,  It takes ~50 minutes to upload a little over 1GB.  SWUpdate client reports 406 error, hawkBit doesn't serve up the http-download URL.  Works fine with file <1GB.

**Comment by voltatindell** [comment]
There are two distributions on there now: Bigdist and Smalldist.  The fomer isn't served, while the latter sucessfully downloads.

**Comment by kaizimmerm** [comment]
https://github.com/eclipse/hawkbit/pull/500 fixes that we return 500 correctly and not 406.

**Comment by voltatindell** [comment]
I'm not seeing your commit in the master I'm seeing.  i also spaced and did not setup hawkbit on AWS for nohup; I will do that later this morning.

**Comment by voltatindell** [comment]
I still don't understand why the bigger update is not being served; it seems to upload fine.

**Comment by voltatindell** [comment]
Two distributions (Big, Small) are up there.  Please feel free to check it out, hit it with a client, whatever.

**Comment by voltatindell** [comment]
I blew this again.  I had not deployed an application to AWS and had only run them with a connected shell; using nohup to start the process did not work as I expected, as I am home now and the URL is not responsive.

**Comment by michahirsch** [comment]
@voltatindell that's awesome, thanks a lot for the support.

**Comment by michahirsch** [comment]
@voltatindell I quick checked by using a curl to download the big-file and I thing it's clear to see the problem. 
```
him1imb@sazmw0072 MINGW64 ~/dev/tmp
$ curl http://54.187.2.152:8080/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/big.swu
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337    0   337    0     0    247      0 --:--:--  0:00:01 --:--:--   247{"timestamp":1493792267452,"status":500,"error":"Internal Server Error","exception":"java.lang.OutOfMemoryError","message":"org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space","path":"/DEFAULT/controller/v1/1/softwaremodules/1/artifacts/big.swu"}
```
It's clearly a memory problem within hawkBit because hawkBit calculates the `eTag` of the file which is downloaded which he shouldn't because then the whole file is copied into memory. In the pull-request of  @kaizimmerm https://github.com/eclipse/hawkbit/pull/500/files#diff-9a534f7094f14cb1c91e2d1323570b74R293 he fixed this problem but is not yet on master but will be soon.

**Comment by kaizimmerm** [comment]
Fix is on master

**Comment by voltatindell** [comment]
Yay!  Thanks, guys.
