### ISSUE TITLE
Rollout dropped from GUI, not from database

### ISSUE THREAD

**Issue by sbabic** [eclipse/hawkbit#527]
Hi,

I have seen that, after dropping a rollout from the GUI (accepted after a request from confirm), I cannot create a new rollout with the same name because it still exists. The rollout remains in the database even if it disappears from GUI. I checked inside DB and  "select * from sp_rollout;" reports the (deleted from GUI) old rollout. I have a quite recent build (commit cacb32da1af88aedf7ab7b4c2878f49db530ee8b). Values are just dropped from sp_rollouttargetgroup table, but they still remain in sp_rollout ans sp_rolloutgroup. Is this the desired behaviour ?

Thanks,
Stefano

**Comment by kaizimmerm** [comment]
That is actually intended behavior. The Rollout is kept in the DB as a reference for the actions it run. We only fully delete if there are no actions referencing this rollout (e.g. If it has never run in the first place).

We are aware of the problematic UX. However, the only way to solve this is giving up the idea of a unique name but That will introduce other problems.

**Comment by sbabic** [comment]
Ok - but then why is it possible to delete the rollout ? If it is not desired to delete it, ithe GUI should forbid t it. This lets the user at least understand why a new rollout is not accepted because there is another one with the same name. Currently, rollout is not accepted, but the list is empty and there is no clue for the user to understand why.

**Comment by kaizimmerm** [comment]
I will put some thought into removing these name constraints. I think we should be able to get rid of those.

**Comment by dcd-arnold** [comment]
I have deleted a rollout that caused problems on some clients. Now the rollout is deleted, but the actions are still there causing problems on my client. 

How do I get rid of the deleted rollout's actions?

And I like to point out once more, that this behavior is highly counter intuitive.

**Comment by strailov** [comment]
Hey @dcd-arnold 
This is the so-called "soft delete" because of historical dependencies of an entity. 
You cannot delete entities which have such dependencies ...

**Comment by dcd-arnold** [comment]
@strailov 

"Soft delete" is a factor. I see a problem, if a record is not visible in the UI (because the user deleted the record) but the user cannot:
1. Create new record with the name of the deleted record.
2. The deleted record may still cause actions and the user does not get feedback because it is not shown in the UI.

The record is not deleted, it is hidden without the ability und unhide it. 

>  You cannot delete entities which have such dependencies ...

I *have* deleted such entity. I pressed *delete* and it was gone. However, the rollout's actions remained and I was unable to manipulate them. If this happens in production, this may cause real damage.

There should be no option for the user to delete a record, if the record will not be deleted in a way the user expects. If the record is just hidden and the systems behaves like it is not in-fact deleted. This action should be revertible. Either solution would be acceptable in my eyes. The current situation is a problem. This issue should not be closed. It is still an issue!
