### ISSUE TITLE
Inaccurate Maven dependencies causing configuration issues

### ISSUE THREAD

**Issue by bobrigado** [eclipse/hawkbit#601]
One of the advantages of Spring and Spring Boot is that they support support a pluggable architecture. For instance, although Spring Boot defaults to Tomcat, you can easily substitute other web servers like Jetty.

However, hawkBit (and after the recent refactoring, hawkbit-extensions and hawkbit-examples), has inaccurate dependencies sprinkled throughout the Maven configuration. For instance, the `pom.xml` for the example theme has 10 dependencies (including for the H2 database), none of which are needed.

Perhaps the biggest issue is the use of `spring-boot-start-jetty` in multiple places. As far as I can tell, there is no code that depends on Jetty, except for one instance of `ConcurrentHashSet` in the device simulator. At the same time, this dependency makes it difficult to run with another web server, including integration tests. It seems like it would be much better to follow the DRY principle and put a dependency like the web server in one place (or as few as possible).

**Comment by kaizimmerm** [comment]
Could your state a few examples where you see an "inaccurate dependency"? I have problems to understand what the actual issue is.

hawkBit starters (thats where the jetty starter is defined) work like other Boot starters. They are meant to simplify especially your runtime setup but not mandatory. Plus they can be (like other Boot starters) easily changed (i.e. maven exclude). In fact many people use hawkBit with tomcat.

And of course no code depends on Jetty, only on Servlet API. But Jetty (or another embedded servlet engine) is needed to host hawkBit. Thats why you need one as a dependency at least. But again you can plug another one in as it fits your needs.
