### ISSUE TITLE
When Hawkbit is set on HTTPS protocol, SWUpdate cannot pull the files

### ISSUE THREAD

**Issue by KrupaRajashekar** [eclipse/hawkbit#618]
Hi,

I have set up Hawkbit on my system, to be used along with SWUpdate on a raspberry pi. This setup works fine for http. But when I changed the configuration to use HTTPS protocol, SWupdate cannot pull the files from the update server. It shows an error where it is trying to connect to HTTP again, & fails.

Any idea how I can resolve this?

Thanks,
Krupa.

**Comment by michahirsch** [comment]
I guess you need to ask the question in the [swupdate github project](https://github.com/sbabic/swupdate) and ask @sbabic how to enable swupdate to use ssl. My guess would be that you are using a self-signed certificate in hawkBit server which swupdate not trusts?

**Comment by sbabic** [comment]
Hi Michael,

On 20/12/2017 11:23, Michael Hirsch wrote:
> I guess you need to ask the question in the swupdate github project
> <https://github.com/sbabic/swupdate> and ask @sbabic
> <https://github.com/sbabic> how to enable swupdate to use ssl. My guess
> would be that you are using a self-signed certificate in hawkBit server
> which swupdate not trusts?

He has already asked the ML, someone else answered:

	https://groups.google.com/forum/#!topic/swupdate/bmIkrkoTW1w

He can connect to Hawkbit, but the URL delivered by Hawkbit is http and
not https. I guess he has not set "hawkbit.artifact.url.https.hostname"
or "hawkbit.artifact.url.https.enabled" in his application properties.

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment]
@sbabic 
Thanks, now I think I get the problem that the download-url is shipped as `http` and not `https`. This is because the download-urls can be configured and the default in hawkBit runtime ships the `http` scheme. See https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/resources/hawkbit-artifactdl-defaults.properties

If you check the [hawkbit-runtime cloudsandbox configuration](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties) you see how to change the download-urls.

If you use the `domainRequest` placeholder it actually should check automatically the scheme see https://github.com/eclipse/hawkbit/blob/67a4677ef63e9e439ceaa710437da0a226964644/hawkbit-core/src/main/java/org/eclipse/hawkbit/api/PropertyBasedArtifactUrlHandler.java#L59

Cheers,
Michael

**Comment by KrupaRajashekar** [comment]
Thanks a lot @michahirsch ! Changing hawkbit-artifactdl-defaults.properties file made it work!

Cheers,
Krupa.

**Comment by michahirsch** [comment]
@KrupaRajashekar 👍  - you don't need necessarly changing the property in the default. You can also overwrite it in your application.properties or via environment.

Glad it helped.

**Comment by epoch1970** [comment]
Is this documented somewhere? Outside a random mailing list post I mean.
