### ISSUE TITLE
DMF API: Cancel Download does not contain enough information

### ISSUE THREAD

**Issue by ertanden** [eclipse/hawkbit#639]
I'm experimenting with the DMF API and I'm kind of stuck in implementing the Cancel Download workflow.

Right now, the CANCEL_DOWNLOAD message has no information about the "actionId" or "softwareModuleId" however the response (UPDATE_ACTION_STATIS) is supposed to have that information in the payload.

If I don't send a proper UPDATE_ACTION_STATUS response, then the CANCEL_DOWNLOAD message keeps being sent every time after a THING_CREATED message.

Any ideas?

**Comment by michahirsch** [comment]
Hi @ertanden 

there is actually the `actiondId` within the DMF AMQP message as `long` in the body of the message. Maybe not the best to just send the `actionId` as long in the body. I guess there is missing the json-document in the body which should probably look like 
```
{
   "actionId" : 1
}
```

The current message looks like
```
(
   Body:'2' 
   MessageProperties [
              headers=
               {    topic=CANCEL_DOWNLOAD, 
                    content-type=application/json, type=EVENT, 
                    tenant=DEFAULT, 
                    __TypeId__=java.lang.Long, 
                   thingId=dmfSimulated0}, 
                   consumerQueue=simulator_receiver
........
)
```

I'll keep this issue open as bug for the DMF cancel message body content to serve `application/json` instead of the just the `actionId` as long value.

Hope this helps,
Cheers,
Michael

**Comment by ertanden** [comment]
@michahirsch Thanks for the reply, indeed it helps, so I'm not stuck now. 

I didn't realize that `actionId` was actually being sent in the body, I guess the documentation also didn't help because it didn't mention that (https://www.eclipse.org/hawkbit/documentation/interfaces/dmf-api.html).
