### ISSUE TITLE
Enable CORS for use in different UI implementations

### ISSUE THREAD

**Issue by MTA1711** [eclipse/hawkbit#708]
Hello ,

We are currently trying to build a custom UI that will display some information from hawkbit. We succefully manage to install Hawkbit and we are able to request  API endpoint via CURL as documentation explains.
An issue occurs when we are doing a request via a web browser, same request that works with curl doesn't work via a browser. 

We always have that error :

OPTIONS http://localhost:8080/rest/v1/softwaremodules 401 (An Authentication object was not found in the SecurityContext)
Failed to load http://localhost:8080/rest/v1/softwaremodules: Response for preflight has invalid HTTP status code 401.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/rest/v1/softwaremodules. (Reason: CORS preflight channel did not succeed)

It seems like Hawkbit API endpoint doesn't allow CORS.

Resquest using curl
`curl -X GET http://10.69.1.131:8080/rest/v1/softwaremodules -H 'authorization: Basic YWRtaW46YWRtaW4='
`

Request in html file

`
function requestHawkbit() {
		var xhr = new XMLHttpRequest();
        xhr.withCredentials = true;

        xhr.addEventListener("readystatechange", function () {
        if (this.readyState === 4) {
            console.log(this.responseText);
        }
        });

        xhr.open("GET", "http://localhost:8080/rest/v1/softwaremodules");
        xhr.setRequestHeader("authorization", getBasicAuthHeader({username: "admin", password: "admin"}));

        xhr.send();
	}
	
	function getBasicAuthHeader(user) {
		return 'Basic ' + btoa(user.username + ':' + user.password);
	}
`

**Comment by schabdo** [comment]
First of all, sorry about the late reply! I'm glad to see that you're building a none Java based UI.
Indeed you're totally right. Seems that nobody gave it a try before. According the Spring docs in order to enable `CORS` there is some additional configuration of `Spring Security` required:  
https://docs.spring.io/spring-security/site/docs/4.1.x/reference/html/cors.html

It never crossed our minds since current UI is connected directly to the repository. We definitely have to fix this!

**Comment by akumlehn** [comment]
We also ran into this issue, while trying to display the hawkbit status in our internal dashboard.

Question: What's the actual todo here? If you can point me in a direction to integrate Spring`s `CorsFilter`, then I may be able to contribute some time.

**Comment by laverman** [comment]
@bogdan-bondar do you think you could give a pointer to @akumlehn ?

**Comment by bogdan-bondar** [comment]
Hi @akumlehn ! 
I have already opened the PR for the CORS: https://github.com/eclipse/hawkbit/pull/854

You can checkout the  corresponding branch and specify the following properties in _application.properties_ file:
`hawkbit.server.security.cors.enabled=true
hawkbit.server.security.cors.allowedOrigins=http://origin1,http://origin2`

You could also specify the allowed headers and methods instead of defaults with:
`hawkbit.server.security.cors.allowedHeaders=Content-Type,Authorization,Accept
hawkbit.server.security.cors.allowedMethods=GET,POST,HEAD`

Hope it solves your problem, feel free to contact me in case of some issues!

**Comment by schabdo** [comment]
Fixed by #854. Thanks @bogdan-bondar!
