### ISSUE TITLE
Auto-assignment filter should allow assignment of soft updates 

### ISSUE THREAD

**Issue by oo7amitsharma** [eclipse/hawkbit#716]
I have a requirement to provide soft update to the devices. So there is no option available for selection of update type(soft/force/schedule) while setting up auto-assigned at filter.
Is there any way to do this. Can any one please help?

There is an option available in the rollout section for selecting update type(soft). But if the devices satisfy the filter condition after cofigure rollout. then devices are not getting update.

![image](https://user-images.githubusercontent.com/13762560/43719225-ccaf1630-99aa-11e8-891a-181aaf96239b.png)

**Comment by laverman** [comment]
Hi @oo7amitsharma , 
unfortunately, there is not mechanism to select the update type (it's always `forced`).However, it would be a great improvement for hawkBit, if it would be configurable. Therefore, I'd like to encourage you to contribute such an extension😊. 

Regarding your comment on rollouts: True, once a rollout is configured, its scope does not change, even if more devices fit the target filter. We are convinced, that this should be this way, since it makes rollouts more deterministic. Do you agree?

-Jeroen

**Comment by laverman** [comment]
@Molkenbur this sounds like a similar requirement that you mentioned on [Gitter](https://gitter.im/eclipse/hawkbit?at=5b413390bd92d807829c6a2f)? Maybe you can collaborate on this?
