### ISSUE TITLE
Failure during "mvn clean install"

### ISSUE THREAD

**Issue by Howlinmoon** [eclipse/hawkbit#752]
I am attempting to install from source on a pretty much stock Ubuntu 18.04 64bit system.

The tests seem to run great - but then they bomb in the JPA section.

[INFO] hawkBit :: Repository :: Test Utilities ............ SUCCESS [  0.650 s]
[INFO] hawkBit :: Repository :: JPA Implementation ........ FAILURE [05:17 min]
[INFO] hawkBit :: Security Integration .................... SKIPPED

Looking through the voluminous output generated, there are numerous exceptions shown.
So as not to clutter up this issue submission with a huge log file - here is a link to it instead:
[https://www.bifftech.com/hawkbit_errors.txt](https://www.bifftech.com/hawkbit_errors.txt)

I tried 3 different clean installs and each failed in the same way, so it doesn't appear to be a random issue.

Jim

**Comment by schabdo** [comment]
I'm sorry to hear that. Maybe I can help out: Which JDK version are you using?

```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

The shown errors `Objenesis java.lang.reflect.InvocationTa...` usually indicate that some reflection calls went wrong. These are the only two tests in hawkBit driven by `PowerMock` (which does a lot of reflection magic).

May I also ask you to have a look at the test reports: 
```
/home/biff/Downloads/hawkbit/hawkbit-repository/hawkbit-repository-jpa/target/surefire-reports
```
Maybe you'll find a more detailed stack trace from test execution there to share with us? 
In the meanwhile in order to skip execution of test you could try `mvn clean install -DskipTests`. 
So you're at least able to build hawkBit from source.
