### ISSUE TITLE
Cannot build project hawkbit-repository-jpa in Eclipse

### ISSUE THREAD

**Issue by bolddp** [eclipse/hawkbit#781]
I've cloned hawkbit to evaluate it for a POC, and I cannot get it to build in Eclipse. It's the hawkbit-repository-jpa project that fails, and hundreds of errors concerning that files named Jpa*_ is cannot be found are generated, e.g. JpaAction_.

I've found some indications that this might be related to the eclipselink-maven-plugin, but I'm not sure.

Has anybody come across this and can provide help?

**Comment by schabdo** [comment]
Your're totally right: The missing classes will be generated by the `eclipselink-maven-plugin`.
After you built HawkBit for the first time you have to add `⁨target⁩/⁨generated-sources⁩/⁨apt⁩` as source folder to `hawkbit-repository-jpa` within Eclipse. Otherwise Eclipse is not able to find them.

![jpa-source-folder](https://user-images.githubusercontent.com/18215905/51101891-fc9e7d80-17dc-11e9-9cab-f6d8e5cf171e.png)

Hope this solves your issue.

**Comment by bolddp** [comment]
It works, thanks a lot! I was focused on trying to add the **classes** folder this way.
