### ISSUE TITLE
Connect and Update Virtual Raspberry Pi with Hawkbit

### ISSUE THREAD

**Issue by AnbazhakanSubramaniam** [eclipse/hawkbit#876]
Hello Everyone, 

I would like to connect and update **"Virtual Raspberry Pi"** with **"Hawkbit"**.
I would be grateful if you could guide me to achieve this if its feasible.

Thanks &Regards,
Anbu

**Comment by laverman** [comment]
Hi, 

since hawkBit provides "server-side" functionality for software updates, a client is required running on your Pi connecting to hawkBit. There are oss client implementations available such as [SWUpdate](https://github.com/sbabic/swupdate), or [RAUC](https://github.com/rauc/rauc), or if you are more into Java and fine with an example implementation you can use [hawkBit's device simulator](hawkBit Device Simulator). 

Once you set up hawkBit on your "back-end" and installed a client on your Pi, you can connect the client to hawkBit. We can have a detailed look at that, once we are done with step one ;-)

**Comment by AnbazhakanSubramaniam** [comment]
Hi, 

Thanks a lot for the details, I will check this out and contact you in case if I need support :)

Regards,
Anbu

**Comment by shailesharya** [comment]
> Hi,
> 
> since hawkBit provides "server-side" functionality for software updates, a client is required running on your Pi connecting to hawkBit. There are oss client implementations available such as [SWUpdate](https://github.com/sbabic/swupdate), or [RAUC](https://github.com/rauc/rauc), or if you are more into Java and fine with an example implementation you can use [hawkBit's device simulator](hawkBit Device Simulator).
> 
> Once you set up hawkBit on your "back-end" and installed a client on your Pi, you can connect the client to hawkBit. We can have a detailed look at that, once we are done with step one ;-)

Could you please provide detailed steps in how to connect raspberry Pi with hawkbit update server?
