### ISSUE TITLE
Hawkbit project roadmap

### ISSUE THREAD

**Issue by xyklex** [eclipse/hawkbit#889]
Hi @schabdo, does Hawkbit Project has a project roadmap to know what we can expect long/short term, and be able to help and plan ahead.

Thanks.

**Comment by schabdo** [comment]
Each year at [EclipseCon Europe's Community Day](https://www.eclipsecon.org/europe2019/eclipse-community-day) we present project update to the audience. We usually publish a link to the shown material afterwards on project's [Gitter channel](https://gitter.im/eclipse/hawkbit) and the [community section](https://www.eclipse.org/hawkbit/community).

I personally expect to see OpenID connect support in near future (since PR is already there), Vaadin 8 for UI and prioritization of multi-assignments. However there is no classical project roadmap as you might expect. So stay tuned for the next update on 21st of October given by our project lead.

Hope this helps to get at least a glimpse of what's ahead and of course help is always appreciated.

**Comment by xyklex** [comment]
Thanks for the answer @schabdo, very appreciated, we are moving our hawkbit deployment to production on the company I work for, we just have approximately 30 devices around US but we expect to have >500 next year, so I will be following any news related to the project, and try to help in anything I can.

I'll look forward to know what EclipseCon brings, thanks.

**Comment by schabdo** [comment]
Sounds awesome! Welcome.

**Comment by schabdo** [comment]
@xyklex community day took place last week. Slides shown by @laverman are available [here](https://www.eclipse.org/hawkbit/slides/community-day-2019.html#/8). Feel free to reach out to him in case you have questions

**Comment by xyklex** [comment]
@schabdo Thanks for the information!
