### ISSUE TITLE
Tracking live status of real-target connected to hawkbit server

### ISSUE THREAD

**Issue by khaleelarya** [eclipse/hawkbit#921]
Hello 

I’m able to update my target with hawk-bit server and rauc client is running in my target which receives the bundles from hawk-bit server.
I would like to know the status of my target before doing an update(whether it is alive or not), Is there any option to check the status of target  and display in the hawk-bit server UI.

Regards
khaleel

**Comment by schabdo** [comment]
Yes, indeed there is a polling status indicating whether device is polling within expected time interval or not. You could even create a filter for overdue devices. Status is shown on Deployment view next to the target (clock icon means "alive"). There is also tooltip available for this icon:

![overdue](https://user-images.githubusercontent.com/18215905/72145097-08923080-339a-11ea-88a5-6d2e743086db.png)

**Comment by khaleelarya** [comment]
Thanks for the comment and I have seen the effect in polling status label based on target availability.
But if I want to see the updated status of polling, I have to restart the UI manually.
can't the polling status automatically get updated instead of restarting UI manually?

**Comment by schabdo** [comment]
> But if I want to see the updated status of polling, I have to restart the UI manually.

I see. Indeed that's true. You have to refresh the page manually in order to get latest poll

> Can't the polling status automatically get updated instead of restarting UI manually?

Push of live poll status for each device is suppressed explicitly (cf. [TARGET_UPDATE_EVENT_IGNORE_FIELDS](https://github.com/eclipse/hawkbit/blob/master/hawkbit-repository/hawkbit-repository-jpa/src/main/java/org/eclipse/hawkbit/repository/jpa/model/JpaTarget.java#L92)). Think of thousands of devices polling every minute: UI would flicker quite a lot showing update after update not to mention the internal event traffic. Having this said, if you just remove "lastTargetQuery" from the list you should get UI updates on every poll
