### ISSUE TITLE
"Custom Target Filter" using query language in rollout creation

### ISSUE THREAD

**Issue by Informatic** [eclipse/hawkbit#922]
Hey!

I'd like to create a rollout with manually entered target filter query. This seems to be supported via management API (https://www.eclipse.org/hawkbit/apis/mgmt/rollouts/ POST `targetFilterQuery` argument), but doesn't seem to be possible when creating the rollout using Vaadin frontend - select box with editable text always falls back to selecting some (nearest matching name-wise?) predefined target filter when changing selected form field.

**Comment by schabdo** [comment]
You're totally right. UI only accepts pre-defined filters to choose from in order to keep it descriptive (and displayable) for the user. Internally UI will create the rollout with the filter query (like the REST call). So it would be possible to accept a string here as well. But keep in mind that filter syntax may become very long and complex. Furthermore a rollout could be created with an advanced group definition (one additional filter per group). I'm not sure how to put all this (incl. autocompletion for filter syntax) in this tiny dialog
