### ISSUE TITLE
Add Stackoverflow tag for Hawkbit

### ISSUE THREAD

**Issue by JulianFeinauer** [eclipse/hawkbit#923]
Hi folks,

today I discussed with @schabdo about having a hawkbit tag for Stackoverflow. Its a great plattform and it would be cool to be able to give people support there (especially as its pretty visible for devs / via google).

What do others think?

**Comment by schabdo** [comment]
Thanks for bringing this to our attention. Committer folks would be happy to support this initiative and update the contribution guide accordingly. However the main problem is that nobody from the project has enough reputation to create a permanent tag on Stackoverflow

**Comment by schabdo** [comment]
@laverman @kaizimmerm What do you guys think? `eclipse-hawkbit` would be a proper tag since other Eclipse projects already use e.g. `eclipse-ditto` or `eclipse-hono`

**Comment by JulianFeinauer** [comment]
I already talked to @chrisdutz who could arrange the tag (he should have enough rights...)

**Comment by chrisdutz** [comment]
Hi all,

in order to do so, I would need to tag a specific question with the tag … so if you send me a link to a stackoverflow question and the list of tags you want to have, I’ll take care of that.

Chris



Von: Julian <notifications@github.com>
Antworten an: eclipse/hawkbit <reply@reply.github.com>
Datum: Freitag, 10. Januar 2020 um 17:17
An: eclipse/hawkbit <hawkbit@noreply.github.com>
Cc: Christofer Dutz <christofer.dutz@c-ware.de>, Mention <mention@noreply.github.com>
Betreff: Re: [eclipse/hawkbit] Add Stackoverflow tag for Hawkbit (#923)


I already talked to @chrisdutz<https://github.com/chrisdutz> who could arrange the tag (he should have enough rights...)

**Comment by laverman** [comment]
I would love to see questions being raised in Stackoverflow instead of Github. 👍 
I'd also support the notion for the tag "eclipse-hawkbit", however, it seems that there is already a "hawkbit" tag. 
Is there a way to "rename" the tag? Otherwise we may just need to introduce a new one.

**Comment by laverman** [comment]
Already available hawkBit questions:
https://stackoverflow.com/questions/58063892/401-error-when-trying-get-request-to-hawkbit-server-with-gateway-security-token
https://stackoverflow.com/questions/56213957/how-to-resolve-error-when-connect-hawkbit-with-mariadb
https://stackoverflow.com/questions/54123372/eclipse-hawkbit-rest-api-is-not-working-with-large-file-upload

**Comment by schabdo** [comment]
> Otherwise we may just need to introduce a new one

Creating a new tag requires 1500 reputation as well

**Comment by schabdo** [comment]
@chrisdutz thanks for offering your help. Highly appreciated and urgently needed! So since @laverman agreed to "eclipse-hawkbit" may I ask you to tag [this question](https://stackoverflow.com/questions/58063892/401-error-when-trying-get-request-to-hawkbit-server-with-gateway-security-token) additionally with "eclipse-hawkbit". I already prepared #926  to add Stack Overflow as communication channel to hawkBit

**Comment by chrisdutz** [comment]
Ok … I created the new tag.

Don’t know if it has to be confirmed by someone else though.
As a posting can’t contain more than 5 tags, I removed the “hawkbit” tag.

Chris

Von: Dominic Schabel <notifications@github.com>
Antworten an: eclipse/hawkbit <reply@reply.github.com>
Datum: Freitag, 17. Januar 2020 um 17:33
An: eclipse/hawkbit <hawkbit@noreply.github.com>
Cc: Christofer Dutz <christofer.dutz@c-ware.de>, Mention <mention@noreply.github.com>
Betreff: Re: [eclipse/hawkbit] Add Stackoverflow tag for Hawkbit (#923)


@chrisdutz<https://github.com/chrisdutz> thanks for offering your help. Highly appreciated and urgently needed! So since @laverman<https://github.com/laverman> agreed to "eclipse-hawkbit" may I ask you to tag this question<https://stackoverflow.com/questions/58063892/401-error-when-trying-get-request-to-hawkbit-server-with-gateway-security-token> additionally with "eclipse-hawkbit". I already prepared #926<https://github.com/eclipse/hawkbit/pull/926> to add Stack Overflow as communication channel to hawkBit

**Comment by schabdo** [comment]
Awesome, thanks a lot @chrisdutz! 

@laverman if we hurry up Stack Overflow announcement could be done in the context of our [0.3.0M6](https://github.com/eclipse/hawkbit/milestone/21?closed=1) milestone

**Comment by chrisdutz** [comment]
I’m happy to help out … especially if it requires so little work 😉

Chris

Von: Dominic Schabel <notifications@github.com>
Antworten an: eclipse/hawkbit <reply@reply.github.com>
Datum: Dienstag, 21. Januar 2020 um 09:04
An: eclipse/hawkbit <hawkbit@noreply.github.com>
Cc: Christofer Dutz <christofer.dutz@c-ware.de>, Mention <mention@noreply.github.com>
Betreff: Re: [eclipse/hawkbit] Add Stackoverflow tag for Hawkbit (#923)


Awesome, thanks a lot @chrisdutz<https://github.com/chrisdutz>!

@laverman<https://github.com/laverman> if we hurry up Stack Overflow announcement could be done in the context of our 0.3.0M6<https://github.com/eclipse/hawkbit/milestone/21?closed=1> milestone

**Comment by schabdo** [comment]
hawkBit officially supports Stack Overflow now
