### ISSUE TITLE
No "weight" field present in UI in case a user enables "multiple distribution"

### ISSUE THREAD

**Issue by vipulbhatia** [eclipse/hawkbit#940]
There is no field present in Auto-Assignment Distribution Set under Target Filters UI to provide a "weight" from 0 to 1000 in case a user enables "Allow parallel execution of multiple distribution set assignments and rollouts" from System Config.

**Comment by schabdo** [comment]
Thanks for filing this issue. Glad to see that you're already using the new multi assignment feature. Indeed this part is still missing. We decided to implement this feature in stages because it's simply too big for a one-shot pull request. Long story short, good news PR for the UI is heading towards master

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
