### ISSUE TITLE
Token when downloading artifacts

### ISSUE THREAD

**Issue by sbabic** [eclipse/hawkbit#941]
In case of tokens for athentication, I am unsure if the token is verified by the server when artefacts are downloaded in case the software modules are put on the Hawkbit server. Generally, I send the token for both DDI API and to get the files. Hawkbit does not complain about it. But a use case is when the artefacts are stored on AWS and AWS has its own authentication mechanism: AWS complain if the token is sent in the headers. I see that token makes less sense when artefact are downloaded (just for DDI API is important), and I will always drop it during a download, but I am unsure if Hawkbit complains (or will complain in future) if no token is passed to get a software module.

Regards,
Stefano

**Comment by schabdo** [comment]
> I am unsure if the token is verified by the server when artefacts are downloaded in case the software modules are put on the Hawkbit server

hawkBit verifies the token even for downloading files. For example this will always return HTTP 401 in case no token is provided in the header: 
```
GET https://hawkbit.eclipse.org/DEFAULT/controller/v1/abc/softwaremodules/1/artifacts/awesome.txt
```
However the validation of tokens can be disabled by allowing "anonymous" download in system config view:
<img width="463" alt="Screenshot 2020-03-12 at 11 54 12" src="https://user-images.githubusercontent.com/18215905/76514490-3e19cf80-6458-11ea-98a3-93d1efe1d4b3.png">

**Comment by schabdo** [comment]
> But a use case is when the artefacts are stored on AWS and AWS has its own authentication mechanism

Indeed, this is a tricky one. I think it depends on the setup of the server. If you return a download URL pointing directly to S3, hawkBit is not involved thus couldn't validate the tokens. I assume AWS is complaining due to the unexpected value of the header, right? (cf. [Authentication Header](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader))

> [...] token makes less sense when artefact are downloaded [...] and I will always drop it during a download, but I am unsure if Hawkbit complains (or will complain in future) if no token is passed to get a software module

hawkBit is already today complaining if the token is missing while getting the software module

Hope this helps to answer your questions

**Comment by sbabic** [comment]
Right - AWS is complaining due to unexpected header. By dropping the header , works. Thanks for clarification, it is then clear to me. However, the client has to solve itself when it has to send the authentication header and when not. Client just gets the URL of the Software Module: it could parse it and check if first part (address) corresponds to the Hawkbit Server for DDI, but I guess this is a very weak solution if there is an alias for the name. Maybe the client should just have a configuration option that enabloe or disable to send the authentication header by downloading a Software Module.
Anyway, thanks for answer !

**Comment by schabdo** [comment]
> Maybe the client should just have a configuration option that enabloe or disable to send the authentication header by downloading a Software Module

Exactly, I think this provides the most flexibility for both (server and client) because I could also think of a setup out there where hawkBit is just proxying download requests from S3 by means the returned download URL from DDI API is pointing to hawkBit server and the server is serving files from S3 transparently for the client

**Comment by schabdo** [comment]
@sbabic I close this issue for now. Please reach out or just reopen it in case you have further questions or something is still open
