### ISSUE TITLE
`mvn clean install` warnings on fresh clone

### ISSUE THREAD

**Issue by dns2utf8** [eclipse/hawkbit#954]
Hi all

I am new to this domain. When following the tutorial, These warnings jumped at me when trying to set hawkbit up:
```bash
$ mvn clean install
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Am I doing something wrong here?

Running on Ubuntu 19.10 with all Updates installed.

Cheers,
Stefan

**Comment by schabdo** [comment]
Thanks for bringing this to our attention. It seems that you're using JDK > 8 in order to build hawkBit. Unfortunately hawkBit is not yet ready for building with JDK < 8. We are currently working on migrating to a new VAADIN version (e.g. https://github.com/eclipse/hawkbit/issues/778#issuecomment-452627037) , which is a prerequisite for being JDK > 8 capable
