### ISSUE TITLE
Provide hawkbit in a sandbox

### ISSUE THREAD

**Issue by michahirsch** [eclipse/hawkbit#96]
@kartben pointed out it would be very handy to have an running hawkBit in a sandbox for users who want to see and try out the hawkBit example-application without cloning and compiling the whole hawkBit-project. 

* For this the hawkBit example app should run on a public available infrastructure (e.g. eclipse, bluemix, etc.)
* The hawkBit example app must be protected that not too many devices can be created to overload the system.

**Comment by kartben** [comment]
> The hawkBit example app must be protected that not too many devices can be created to overload the system

We might not even want to have such a limitation at day 1. 

I wonder if you will want to deploy "manually" a SNAPSHOT once in a while, or hook the sandbox to master, and redeploy (therefore restart... and possibly scratch all the user data (for better or worse: it means we don't *need* to really care about how many devices can be created etc since they will go away quite often anyways)) from CI.
Both approaches have pros and cons, I guess it depends whether you also want to use a sandbox as a way to have an always up-to-date integration/testing platform, or if it needs to be a more stable showcase kind of thing.

**Comment by kaizimmerm** [comment]
I prefer having the sandbox open for people to play around and than erase the data from time to time. We could run this installation with h2 in-memory and at startup create a small demo data setup.

**Comment by kartben** [comment]
+1
So eg a cron every week would download latest SNAPSHOT and restart the demo
(+ launch data population scripts), for example?

Le jeu. 17 mars 2016 08:02, Kai Zimmermann <notifications@github.com> a
écrit :

**Comment by michahirsch** [comment]
This sounds good to me, having a cron job and update the master on an public infrastructure :+1: This will also verify that the example app is working.
