### ISSUE TITLE
MD5 hash is outdated with security risks

### ISSUE THREAD

**Issue by embexus** [eclipse/hawkbit#965]
Hawbit uses MD5SUM to ensure the integrity of the downloaded artifacts however MD5 for different security vulnerabilities not recommended:

https://www.win.tue.nl/hashclash/rogue-ca/

It would be great if Hawkbit switch to more robust hash such as sha265 or higher and also nice to have the hash algo as configurable parameter.

**Comment by schabdo** [comment]
Not sure if I understood correctly. I assume you're referring to generated MD5SUM link within the DDI response of the deployment base, right? If so, let me shed some light on this: The link is still kept for API backwards compatibility reasons in order to ensure we won't brake already connected devices out there in the field. Having this said, please note that the response also contains a hash section for every artefact providing `SHA1` and `SHA256` hashes in addition. So just use these or in case you have requirement for more/different algorithm you could add another file to your software module containing the hashes you want to validate against.

```
GET https://hawkbit.eclipse.org/DEFAULT/controller/v1/myDevice/deploymentBase/1

"artifacts": [{
  "filename": "image.zip",
  "hashes": {
    "sha1": "ec81327587f76c99fc8511fed3ad81bdae91e658",
    "md5": "f647bc98ea36706cecc0a29efc43aa2f",
    "sha256": "101e3798131b2d34f61654f3426daf29fc241687f84e0d5a2f25d793ff8cc908"
  },
  "size": 10000,
  "_links": {
    "download-http": {
      "href": "https://hawkbit.eclipse.org/DEFAULT/controller/v1/myDevice/softwaremodules/1/artifacts/image.zip"
    },
    "md5sum-http": {
      "href": "https://hawkbit.eclipse.org/DEFAULT/controller/v1/myDevice/softwaremodules/1/artifacts/image.zip.MD5SUM"
    }
  }
}]
```

The link you provided is about the usage of MD5 for CA certificates within encrypted TLS/SSL communication. So I think besides a potential hash collision the risks don't apply to files
