### ISSUE TITLE
enable cors and https

### ISSUE THREAD

**Issue by JuliusHarald** [eclipse/hawkbit#971]
Hi,

I ran Hawkbit version 0.2.4 as docker containers. I mounted a custom `application.properties` file next to the jar-file to enable https with the following configurations:

`server.ssl.key-store=/opt/hawkbit/key.jks
server.ssl.key-store-passsword=<passwort>
server.ssl.key-password=<passwort>
server.ssl.enabled-protocols=TLSv1.2
server.ssl.trust-store=/pfad/zu/truststore.jks
server.ssl.trust-store-password=<passwort>
server.ssl.client-auth=need
security.require-ssl=true` 

I shortly upgraded to version 0.3.0 to enable CORS, but now I get: ` Error code: SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT`

I can put `server.ssl.client-auth=none` to make it work, bit that is not what I want for good.
Do you guys have an idea whats causing the error?

thanks

**Comment by schabdo** [comment]
> Do you guys have an idea whats causing the error?

AFAIK Spring Boot removed the property `security.require-ssl` in a more recent version. So you could try to set `hawkbit.server.security.require-ssl=true` instead. If this is not working for you the fact that `server.ssl.client-auth=none` is solving your issue I'd assume that it could be caused by a client certificate mismatch. In order to gain more insight in the latter I'd recommend to have a look into the SSL/TLS communication. Hope this helps
